package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

type Options struct {
	PackageName   string
	WriteRootFile bool
	WriteReadme   bool
	WriteTests    bool
}

func Create(folder string, options Options) error {
	if options.PackageName == "" {
		return fmt.Errorf("package name is required")
	}

	if folder == "" {
		return fmt.Errorf("folder path is required")
	}

	if err := os.MkdirAll(folder, 0o755); err != nil {
		return err
	}

	if options.WriteRootFile {
		content := fmt.Sprintf("package %s\n", options.PackageName)
		filePath := filepath.Join(folder, fmt.Sprintf("%s.go", options.PackageName))
		if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
			return err
		}
	}

	if options.WriteTests {
		if err := writeTestFile(folder, options.PackageName); err != nil {
			return err
		}
	}

	if !options.WriteReadme {
		return nil
	}

	readme := fmt.Sprintf("# %s\n\nGenerated by go-toolkit.\n", options.PackageName)
	readmePath := filepath.Join(folder, "README.md")
	return os.WriteFile(readmePath, []byte(readme), 0o644)
}

func writeTestFile(folder string, packageName string) error {
	testName := testFunctionName(packageName)
	content := fmt.Sprintf(`package %s

import "testing"

func %s(t *testing.T) {}
`, packageName, testName)

	path := filepath.Join(folder, fmt.Sprintf("%s_test.go", packageName))
	return os.WriteFile(path, []byte(content), 0o644)
}

func testFunctionName(packageName string) string {
	parts := strings.FieldsFunc(packageName, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})

	if len(parts) == 0 {
		return "TestPackage"
	}

	var builder strings.Builder
	builder.WriteString("Test")
	for _, part := range parts {
		builder.WriteString(capitalize(part))
	}

	return builder.String()
}

func capitalize(value string) string {
	if value == "" {
		return ""
	}

	first, size := utf8.DecodeRuneInString(value)
	if first == utf8.RuneError && size == 1 {
		return value
	}

	return string(unicode.ToUpper(first)) + value[size:]
}
