package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

type Options struct {
	PackageName string
	WriteIndex  bool
	WriteReadme bool
}

func Create(folder string, options Options) error {
	if options.PackageName == "" {
		return fmt.Errorf("package name is required")
	}

	if folder == "" {
		return fmt.Errorf("folder path is required")
	}

	if err := os.MkdirAll(folder, 0o755); err != nil {
		return err
	}

	if !options.WriteIndex {
		if !options.WriteReadme {
			return nil
		}
	} else {
		content := fmt.Sprintf("package %s\n", options.PackageName)
		filePath := filepath.Join(folder, "index.go")
		if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
			return err
		}
	}

	if !options.WriteReadme {
		return nil
	}

	readme := fmt.Sprintf("# %s\n\nGenerated by go-toolkit.\n", options.PackageName)
	readmePath := filepath.Join(folder, "README.md")
	return os.WriteFile(readmePath, []byte(readme), 0o644)
}
